name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: ./.vscode/setup.sh

      - name: Build project
        run: ./.vscode/build.sh

      - name: Get version from package.json
        id: extract_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: List files in out directory
        run: ls -l ./out/

      - name: Rename archive with version
        run: sudo mv ./out/Decky-Undervolt.zip ./out/Decky-Undervolt-${{ env.VERSION }}.zip

      - name: Create Release

        id: create_release
        uses: actions/create-release/@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload to Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/Decky-Undervolt-${{ env.VERSION }}.zip
          asset_name: Decky-Undervolt-${{ env.VERSION }}.zip
          asset_content_type: application/zip